### ISSUE TITLE
Deploying on Cloudflare

### ISSUE THREAD

**Issue by superhighfives** [chimame/remix-prisma-d1-on-cloudflare-pages#1]
Hey @chimame! This is awesome.

I've tried deploying to Cloudflare with it, but the `getLoadContext` doesn't seem to be working on that end, and I get a undefined on `db`.

```ts
// Shared implementation compatible with Vite, Wrangler, and Cloudflare Pages
export const getLoadContext: GetLoadContext = async ({ context }) => {
  return {
    ...context,
    db: await connection(
      context.cloudflare.env.DB,
    ),
  }
}
```

Wondered if you'd had any luck deploying?

**Comment by chimame** [comment]
Hi @superhighfives 

Is the program below in `load-context.ts`?
```ts
import { connection } from './app/database/client'

// or

declare module "@remix-run/cloudflare" {
  interface AppLoadContext {
    cloudflare: Cloudflare;
    db: Awaited<ReturnType<typeof connection>>
  }
}
```

If it exists, either the program description is missing in `functions/[[path]].ts` or the settings in `vite.config.ts` are missing.

```ts
// functions/[[path]].ts
import { getLoadContext } from "../load-context";

export const onRequest = createPagesFunctionHandler({ build, getLoadContext });
```

```ts
// vite.config.ts
import { getLoadContext } from "./load-context";

export default defineConfig({
  plugins: [remixCloudflareDevProxy({ getLoadContext }), remix(), tsconfigPaths()],
});
```

**Comment by chimame** [comment]
If it does not work after deploying to Cloudflare, the `wrangler.toml` settings will not be reflected in the `wrangler` used in this Remix. Therefore, you will need to configure D1 on the Cloudflare console.

If you want to reflect the contents of `wrangler.toml` with `wrangler pages deploy`, install the latest version of `wrangler` and it will be reflected at the time of deployment.
https://blog.cloudflare.com/pages-workers-integrations-monorepos-nextjs-wrangler

**Comment by chimame** [comment]
Also, if you bundle Remix and Prisma into the same Cloudflare Workers, the size will exceed 1MB. So it won't work with Cloudflare's free accounts. To get it to work, you'll need to use paid Workers, or deploy Remix and Prisma as separate Cloudflare Workers, as shown in the repositories below.

https://github.com/chimame/connect-remix-and-prisma-d1-using-rpc-on-cloudflare-pages

**Comment by superhighfives** [comment]
This is so cool—thank you! 😊 Turns out it was the `functions/[[path]].ts` file that I'd missed. 🙌 

Just came across the 1mb limit. Will dig in.

**Comment by chimame** [comment]
Please ask again if I can answer it.
Happy Hacking! :wink:
